### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by bretonics** [bretonics/seqR#3]
- [ ] Stdout to log file
## On success
- [ ] Email with result files
## On Failure
- [ ]  Email point of exit
- [ ] #1
